### ISSUE TITLE
Is this method deprecated in ansible 2.2?

### ISSUE THREAD

**Issue by EugenMayer** [chrismeyersfsu/provision_docker#24]
I am fairly new to ansible, so i might really add FUD here, so just punch me.

Could it be that this playbook is kinda outdated due to ansible 2.2. introducing native docker features? 

running the playbook i also get

```
[DEPRECATION WARNING]: docker is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale..
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
```

But in general i run into issues like 
```
failed: [localhost -> localhost] (item=localhost) => {"failed": true, "item": "localhost", "msg": "`docker-py` doesn't seem to be installed, but is required for the Ansible Docker module."}
```

where i am not really sure, that is an issue on the client or on the host running ansible ( osx / brew based installation of ansible 2.2

**Comment by chrismeyersfsu** [comment]
> Could it be that this playbook is kinda outdated due to ansible 2.2. introducing native docker features?
I wouldn't quite put it like that. Yes, Ansible has invested in Docker. This translates to:
* Increased development of Docker modules
* Docker connection plugin
* Ansible Container

You may have heard the most about Ansible container recently. Ansible container is a set of tools to help you build Docker images using Ansible without having to learn the Docker/container ecosystem.

This project does not attempt to hide the use of Docker/containers nor does it presume the user has no knowledge of containers. This product is mainly around the starting/stopping of containers while Ansible Container deals mostly with building images.

> running the playbook i also get

When I first built this role the Docker module for Ansible was in flux. I think the module name has since changed to `docker-container` or something. Thanks for pointing this out.

> But in general i run into issues like

This can be a real pain-in-the-ass. It has to do with where pip puts python packages on your mac + the fact that Ansible hard-codes the python path for modules.

Try this: `which python` should show `/usr/local/bin/python`. That's the python that gets ran when you type `python` on the command line. Now try `whereis python`. You probably get `/usr/bin/python`, that's the python Ansible modules will invoke. Now try to import the docker module using each python interpreter and see which one results in a successful `import docker`.

```
import docker
docker.__file__
```

There are multiple ways to "fix" this. I chose to delete `/usr/bin/python` with a soft link to `/usr/local/bin/python`

 `lrwxr-xr-x  1 root  wheel  21 Oct 11 10:48 /usr/bin/python -> /usr/local/bin/python`

**Comment by EugenMayer** [comment]
Well i wrapped my had arround all this and created a basic playbook with docker_container

```
---
# start our test container
- hosts: localhost
  tasks:
    - name: Create container
      docker_container:
        name: ansibletestserver
        image: debian:jessie
        command: bash

# those would be the test roles whatever we do
- hosts: ansibletestserver
  tasks:
    - name: "test command"
      command: cat '/var/log/supervisor/supervisord.log'

# start our test container
- hosts: localhost
  tasks:
    - name: Create container
      docker_container:
        name: ansibletestserver
        state: absent
```

and this inventory on OSX

```
[me]
localhost ansible_connection=local ansible_python_interpreter=/opt/boxen/pyenv/shims/python

[testcontainers]
ansibletestserver ansible_connection=docker ansible_user=root
```

I finally understood how to fix the docker-py issue (localhost .. connection local..and the python interpreter .. but i found it very confusing when looking at your playbook. I basically understood the issue when setting up docker_containers.

---

Pros:
The method above is superior because it no longer needs ssh on the containers - thus you can simple use any image you find and do not need to create a specific ssh-enabled image ( those are rare  out of very good reasons ).

**I find this a huge plus - since i can test images i have, unmodified.**

Using the docker connection type makes a huge sense and should also be utilized here i guess.

Cons:
i have to create a customer inventory - though for testing reasons, i find this pretty ok.
Nevertheless, when you introduce that docker_container is used and that the containers are configured to be ansible_connection=docker you add what is missing in my part, the dynamic inventory.


----------
Please forgive me, if i really fed it up by any means. Those are my first 2 hours with ansible and i might throw stuff at you which is nonse - be unpolite and tell me straight :)
